#%RAML 0.8
title: Angular Test API
version: 0.1.0
baseUri: angular-test

/:
    description: este endpoint se usa para verificar si hay conexión con el servidor
    get:
        description: este endpoint se usa para verificar si hay conexión con el servidor


/user:    
    get:
        description: retorna todos los usuarios que esten registrados
    post:
        description: Crea un usario
        queryParameters:
            id:
                description: Cedula del usuario
            name:
                description: Nombre del usuario
            lastName:
                description: Apellido del usuario
            age:
                description: Edad del usuario
            profession:
                description: ocupacion del usuario

